--- #YAML:1.0
name:                SOAPjr
version:             1.0.1
abstract:            the love child of SOAP and JR (JSON-RPC)
license:             perl
author:              
    - Rob Manson <robman@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    JSON:                          0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
